---
title: "Simulate IL portfolio"
engine: knitr
---

## 1. Introduction

This document shows a basic example of how to originate and simulate a vintage of loans using the `porsim` package.

## 2. Load Package

First, we load the `porsim` package to make its functions available.

```{r}
#| label: do-imports

# library(porsim)
library(tidyverse)
library(stringr)

```


```{r}
#| label: define-parameters

# Define product parameters
product_mtp <- list(
  product_name = "IL",
  min_amount = 1000,
  max_amount = 250000,
  contract_duration = 1+24, # one for contract creation + number of payments
  interest_per_period = 0.35/12, # APR / 12 because currently, period is month
  time_periods_till_acceleration = 3
)

# Define segment parameters
segment_standard <- list(
  segment_name = "standard_client", # Add a name for the segment
  avg_limit_pct_of_max = 0.50,
  avg_first_balance_pct_of_limit = 0.56,
  default_prob = c(0.05, 0.02, 0.01, 0.005, 0.002),
  debt_sale_recovery_rate = 0.65, 
  early_repayment_rate = c(0.15, 0.08, 0.04, 0.02, 0.01)
)

# # Define segment parameters
# segment_pay_early <- list(
#   segment_name = "early_payer", # Add a name for the segment
#   avg_limit_pct_of_max = 0.80,
#   avg_first_balance_pct_of_limit = 0.5,
#   default_prob = c(0.005),
#   debt_sale_recovery_rate = 0.20, 
#   early_repayment_rate = c(0.8, 1)
# )



# Create a sales plan list
sales_plan_list <- list(
  q1_2025_sales = list(
    product_params = product_mtp,
    segment_params = segment_standard,
    # monthly_loans = c(10, 10, 10),
    monthly_loans = c(57, 171, 288, 148, 137, 246, 164, 144, 178),
    vintage_date = as.Date("2024-12-01") # first day of the month of the sales
  )
  # # NEW: Plan for the early payers starting in Q2
  # q2_2025_early = list(
  #   product_params = product_mtp,
  #   segment_params = segment_pay_early,
  #   monthly_loans = c(10, 10, 10),
  #   vintage_date = as.Date("2025-04-01") # first day of the month of the sales
  # )
)

```


```{r}
#| label: create-vintages

set.seed(4567)

initial_portfolio <- generate_sales(
  sales_plans = sales_plan_list,
  portfolio_name = "MyFirstPortfolio"
)

# See the generated loans (6 total)
# print(initial_portfolio)

```


```{r}
#| label: create-portfolio

set.seed(1234)
portfolio_history <- run_simulation(initial_portfolio)

```


```{r}
#| label: view-portfolio
#| results: asis

# print(portfolio_history[portfolio_history$loan_id == "L2025010001", ])
# print(portfolio_history, n = 20) # Print the first 20 rows -->

```


```{r}
#| label: calculate-metrics
#| tbl-cap: "A summary of the final outcomes for all loans in the simulated portfolio."

calculate_portfolio_metrics(portfolio_history)
# Display the metrics as a table
# knitr::kable(portfolio_metrics)

```


```{r}
calculate_portfolio_metrics_month(portfolio_history)
```



```{r}
portfolio_view(portfolio_history)
```



```{r}
portfolio_history %>% 
  distinct(period_date)

portfolio_history %>% filter(period_date == as.Date("2025-05-30"))
```

