---
title: "Getting Started with portfolioSim"
engine: knitr
---

## 1. Introduction

This document shows a basic example of how to originate and simulate a vintage of loans using the `porsim` package.

## 2. Load Package

First, we load the `porsim` package to make its functions available.

```{r}
#| label: do-imports

library(porsim)
library(tidyverse)
library(stringr)

```


```{r}
#| label: define-parameters

# Define product parameters
product_mtp <- list(
  product_name = "MTP",
  min_amount = 1,
  max_amount = 100,
  contract_duration = 6,
  interest_per_period = 0.022,
  time_periods_till_acceleration = 3
)

# Define segment parameters
segment_standard <- list(
  avg_limit_pct_of_max = 0.80,
  avg_first_balance_pct_of_limit = 0.95
)

# Create a sales plan list
# This plan will create 3 vintages:
# - 1 loan in Jan 2025
# - 2 loans in Feb 2025
# - 3 loans in Mar 2025
sales_plan_list <- list(
  q1_2025_sales = list(
    product_params = product_mtp,
    segment_params = segment_standard,
    monthly_loans = c(1, 2, 3), 
    vintage_date = as.Date("2025-01-31")
  )
)

```


```{r}
#| label: create-vintages

initial_portfolio <- generate_sales(
  sales_plans = sales_plan_list,
  portfolio_name = "MyFirstPortfolio"
)

# See the generated loans (6 total)
print(initial_portfolio)

```


```{r}
#| label: create-portfolio

portfolio_history <- run_simulation(initial_portfolio)

```


```{r}
#| label: view-portfolio
#| results: asis

print(portfolio_history[portfolio_history$loan_id == "L2025010001", ])
# print(portfolio_history, n = 20) # Print the first 20 rows -->

```

