#' @importFrom dplyr %>% group_by summarise mutate ungroup arrange cumsum filter pull first select any_of across left_join rename case_when
#' @importFrom tidyr pivot_longer replace_na
#' @importFrom ggplot2 ggplot aes geom_col geom_line scale_y_continuous labs theme_minimal theme element_text scale_fill_manual scale_color_manual sec_axis
#' @importFrom scales comma
NULL

#' Visualize the performance of a simulated portfolio over time.
#'
#' @description
#' This function generates a plot showing the outstanding principal balance,
#' split into "Normal" and "Past Due" (as stacked columns), and the
#' cumulative cash flow (as a line) over the life of the portfolio.
  #'
  #' @param portfolio_history A tibble containing the full simulation results,
  #'   as generated by `run_simulation()`.
  #'
  #' @return A ggplot object.
  #'
  #' @export
  #' @examples
  #' \dontrun{
  #' # Assuming `portfolio_history` is the result of `run_simulation()`
  #' portfolio_view(portfolio_history)
  #' }
portfolio_view <- function(portfolio_history) {

    # --- 1. Calculate Monthly Aggregates ---
    originated_amount <- portfolio_history %>%
      dplyr::filter(period == 1) %>%
      dplyr::group_by(period_date) %>%
      dplyr::summarise(total_originated = sum(initial_principal))

    monthly_summary <- portfolio_history %>%
      dplyr::group_by(period_date) %>%
      dplyr::summarise(
        outstanding_balance = sum(closing_balance),
        # Calculate the balance of only defaulted/sold loans
        past_due_balance = sum(closing_balance[status %in% c("Defaulted", "Sold")]),
        incoming_payments = sum(payment),
        debt_sale_proceeds = sum(debt_sale_proceeds)
      ) %>%
      dplyr::ungroup() %>%
      dplyr::arrange(period_date) %>%
      dplyr::left_join(originated_amount, by = "period_date") %>%
      dplyr::mutate(total_originated = tidyr::replace_na(total_originated, 0))

    # --- 2. Calculate Cumulative Cash Flow & Balances ---
    plot_data_prep <- monthly_summary %>%
      dplyr::mutate(
        net_cash_flow = (incoming_payments + debt_sale_proceeds) - total_originated,
        cumulative_cash_flow = cumsum(net_cash_flow),
        # Normal balance is the remainder
        normal_balance = outstanding_balance - past_due_balance,
        month = format(period_date, "%Y-%m")
      ) %>%
      dplyr::select(month, `Normal Balance` = normal_balance, `Past Due Balance` = past_due_balance, cumulative_cash_flow)

    # --- 3. Prepare Data for Plotting ---
    plot_data <- plot_data_prep %>%
      tidyr::pivot_longer(
        cols = c(`Normal Balance`, `Past Due Balance`),
        names_to = "balance_type",
        values_to = "balance_amount"
      )

    # --- 4. Create the Plot ---
    max_balance <- max(plot_data_prep$`Normal Balance` + plot_data_prep$`Past Due Balance`, na.rm = TRUE)
    max_cashflow <- max(plot_data_prep$cumulative_cash_flow, na.rm = TRUE)
    # Handle case where max_cashflow could be 0 or negative
    scale_factor <- if (max_cashflow > 0) max_balance / max_cashflow else 1




    ggplot2::ggplot(plot_data, ggplot2::aes(x = month)) +
      # Stacked Columns for Balance
      ggplot2::geom_col(
        ggplot2::aes(y = balance_amount, fill = balance_type),
        position = "stack"
      ) +
      # Line for Cash Flow
      ggplot2::geom_line(
        data = plot_data_prep,
        ggplot2::aes(y = cumulative_cash_flow * scale_factor, group = 1, color = "Cumulative Cash Flow"),
        linewidth = 1.5
      ) +
      # Manual color and fill scales
      ggplot2::scale_fill_manual(
        name = "Balance Type",
        values = c("Normal Balance" = "steelblue", "Past Due Balance" = "firebrick")
      ) +
      ggplot2::scale_color_manual(
        name = "",
        values = c("Cumulative Cash Flow" = "darkgreen")
      ) +
      # Secondary Y-Axis
      ggplot2::scale_y_continuous(
        name = "Outstanding Balance",
        labels = scales::comma,
        sec.axis = ggplot2::sec_axis(
          ~ . / scale_factor,
          name = "Cumulative Cash Flow",
          labels = scales::comma
        )
      ) +
      ggplot2::labs(
        title = "Portfolio Performance Over Time",
        x = "Month",
        caption = "Generated by porsim package"
      ) +
      ggplot2::theme_minimal() +
      ggplot2::theme(
        plot.title = ggplot2::element_text(hjust = 0.5),
        legend.position = "bottom",
        legend.box = "horizontal",
        axis.text.x = ggplot2::element_text(angle = 45, hjust = 1)
      )
  }
